apiVersion: v2
name: infra-webshop
description: PORR AG Infrastructure Self-Service Webshop
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - porr
  - infrastructure
  - self-service
maintainers:
  - name: PORR AG Digital Unit
